title:              Bruno Gauthier
email:              info@brunogauthier.net 
description:        si les chiffres pouvaient parler...
author:             Bruno Gauthier
baseurl:            ""
url:                "https://brunoelgrande.github.io"

# Social Profiles
twitter_username:   
github_username:    brunoelgrande
facebook_username:  
instagram_username:  
linkedin_username:  brunogauthier

# Add your google-analytics ID here to activate google analytics
# google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge  ## Pour highlighing des codes snippets